/* Conformance Test 2.6.0.3:  Ensure reserved words within identifiers are    */
/*                            ignored                                         */
main ()
  {
   int     asmm, auto_1, tbreak, casechar, continue_default, dodoubleelse;
   short   _comp, extended_, inlinee, pascal0, segment_;
   long    enum_external, floatforgoto, ifi, inty, longy, registerreturn;
   float   short2, sizeofF, staticstruct, switch_, typedef0, union_;
   double  unsignedNum, voidT, while_, aconst, isigned, _volatile;

   printf ("Passed Conformance Test 2.6.0.3\n");
  }
