/* Conformance Test 2.6.0.4: Ensure reserved words within strings are ignored */
main ()
  {
   char s0 [] = "asm";
   char s1 [] = "auto";
   char s2 [] = "break";
   char s3 [] = "case";
   char s4 [] = "char";
   char s5 [] = "continue";
   char s6 [] = "default";
   char s7 [] = "do";
   char s8 [] = "double";
   char s9 [] = "else";
   char s10[] = "enum";
   char s11[] = "extern";
   char s12[] = "float";
   char s13[] = "for";
   char s14[] = "goto";
   char s15[] = "if";
   char s16[] = "int";
   char s17[] = "long";
   char s18[] = "register";
   char s19[] = "return";
   char s20[] = "short";
   char s21[] = "sizeof";
   char s22[] = "static";
   char s23[] = "struct";
   char s24[] = "switch";
   char s25[] = "typedef";
   char s26[] = "union";
   char s27[] = "unsigned";
   char s28[] = "void";
   char s29[] = "while";
   char s30[] = "const";
   char s31[] = "signed";
   char s32[] = "volatile";
   char s33[] = "comp";
   char s34[] = "extended";
   char s35[] = "inline";
   char s36[] = "pascal";
   char s37[] = "segment";

   printf ("Passed Conformance Test 2.6.0.4\n");
  }
