/* Conformance Test 2.6.0.5:  Ensure reserved words within comments are       */
/*                            ignored                                         */
main ()
  {
   /* int     auto, break, case, char, continue, default, do, double;   */
   /* long    else, enum, extern, float, for, goto, if, int, long;      */
   /* float   register, return, short, sizeof, static, struct, switch;  */
   /* double  typedef, union, unsigned, void, while, const, signed;     */
   /* short   volatile, asm, comp, extended, inline, pascal, segment;   */

   printf ("Passed Conformance Test 2.6.0.5\n");
  }
