/* Deviance Test 2.5.0.2:  Ensure reserved words cannot be used as identifiers */
main ()
  {
   int       auto;
   int       break;
   int       case;
   int       char;
   int       continue;
   int       default;
   int       do;
   int       double;
   long      else;
   long      enum;
   long      extern;
   long      float;
   long      for;
   long      goto;
   long      if;
   long      int;
   float     long;
   float     register;
   float     return;
   float     short;
   float     sizeof;
   float     static;
   float     struct;
   float     switch;
   double    typedef;
   double    union;
   double    unsigned;
   double    void;
   double    while;
   short     const;
   short     signed;
   short     volatile;
   unsigned  asm;
   unsigned  comp;
   unsigned  extended;
   unsigned  inline;
   unsigned  pascal;
   unsigned  segment;

   printf ("Failed Deviance Test 2.5.0.2\n");
  }
