/* Global declarations for Special Conformance Test 25.0.1 */

extern char ch0 [3];
extern int  i0  [3];
extern long L0  [3];
extern unsigned char uch0 [3];
extern unsigned int  ui0  [3];
extern unsigned long ul0  [3];

extern char * Init_Ch   (char ch []);
extern int  * Init_Int  (int   i []);
extern long * Init_Long (long  L []);
extern unsigned char * Init_UCh (void);
extern unsigned int  * Init_UI  (unsigned int  ui []);
extern unsigned long * Init_UL  (unsigned long ul []);
