/* Special Conformance Test 3.4.0.2:  Ensure #include files can be nested to */
/*                                    a depth of at least 8                  */
/*                                                                           */
/* Other files needed:  spc34021, spc34022, spc34023, spc34024, spc34025     */
/*                      spc34026, spc34027, spc34028                         */

#include "spc34021"
